---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "sni-router.fullname" . }}
spec:
    replicas: 1
    selector:
        matchLabels:
            {{- include "sni-router.selectorLabels" . | nindent 10 }}
    template:
        metadata:
          {{- with .Values.podAnnotations }}
            annotations:
              {{- toYaml . | nindent 16 }}
          {{- end }}
            labels:
              {{- include "sni-router.selectorLabels" . | nindent 16 }}
              {{- if eq (.Values.image.tag | default .Chart.AppVersion) "latest" | or (eq (.Values.image.tag | default .Chart.AppVersion) "snapshot") }}
                refreshImageTag: "{{- randAlphaNum 24 | nospace -}}"
              {{- end }}
        spec:
            {{- with .Values.podSecurityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.nodeSelector }}
            nodeSelector:
                {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.affinity }}
            affinity:
                {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.tolerations }}
            tolerations:
                {{- toYaml . | nindent 14 }}
            {{- end }}
            containers:
                - name: nginx
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
                  command:
                      - /bin/sh
                  args:
                      - "/entrypoint-router.sh"
                  ports:
                      - containerPort: 8080
                        name: http
                        {{- if .values.service.useHostPorts }}
                        hostPort: 80
                        {{- end }}
                      - containerPort: 8081
                        name: metrics
                      - containerPort: 4443
                        name: tls
                        {{- if .values.service.useHostPorts }}
                        hostPort: 443
                        {{- end }}
                  volumeMounts:
                      - mountPath: /etc/nginx/nginx.conf
                        name: config
                        subPath: nginx.conf
                      - mountPath: /entrypoint-router.sh
                        name: config
                        subPath: entrypoint.sh
            volumes:
                - name: config
                  configMap:
                      name: {{ include "sni-router.fullname" . }}-router-config
