---
apiVersion: v1
kind: Service
metadata:
    name: {{ include "sni-router.fullname" . }}
    labels:
        {{- include "sni-router.labels" . | nindent 8 }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: 8080
          targetPort: http
          protocol: TCP
          name: http

        - port: 8081
          targetPort: metrics
          protocol: TCP
          name: metrics

        - port: 4443
          targetPort: tls
          protocol: TCP
          name: tls
    selector:
        {{- include "sni-router.selectorLabels" . | nindent 8 }}
