name: Test and release
on:
    push:

jobs:
    release-chart:
        runs-on: ubuntu-latest
        needs: ["release-docker"]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

            - name: Set up Helm
              uses: azure/setup-helm@v1
              with:
                  version: v3.8.1

            - name: Run chart-testing (lint)
              run: ct lint

            - name: Publish Helm chart
              if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
              uses: stefanprodan/helm-gh-pages@master
              with:
                  token: "${{ secrets.GH_RW_TOKEN }}"
                  charts_dir: helm
                  charts_url: https://riotkit-org.github.io/helm-of-revolution
                  owner: riotkit-org
                  repository: helm-of-revolution
                  branch: gh-pages
                  target_dir: ./
                  commit_username: "${{ env.GITHUB_ACTOR }}"
                  commit_email: "${{ env.GITHUB_ACTOR }}@users.noreply.github.com"

                  app_version: "${{github.ref_name}}"
                  chart_version: "${{github.ref_name}}"
