name: Test and release
on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Helm
              uses: azure/setup-helm@v1
              with:
                  version: v3.8.1

            - name: Linting
              working-directory: helm/sni-router
              run: helm lint ./

            - name: Template and default values check
              working-directory: helm/sni-router
              run: helm template ./

    release-chart:
        runs-on: ubuntu-latest
        needs: ["test"]
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

            - name: Publish Helm chart
              uses: stefanprodan/helm-gh-pages@master
              with:
                  token: "${{ secrets.GH_RW_TOKEN }}"
                  charts_dir: helm
                  charts_url: https://riotkit-org.github.io/helm-of-revolution
                  owner: riotkit-org
                  repository: helm-of-revolution
                  branch: gh-pages
                  target_dir: ./
                  commit_username: "${{ env.GITHUB_ACTOR }}"
                  commit_email: "${{ env.GITHUB_ACTOR }}@users.noreply.github.com"

                  app_version: "${{github.ref_name}}"
                  chart_version: "${{github.ref_name}}"

            - name: Extract version
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: Push to ghcr.io
              uses: appany/helm-oci-chart-releaser@v0.3.0
              with:
                name: helm-sni-router
                repository: riotkit-org
                tag: "${{ env.RELEASE_VERSION }}"
                path: helm/sni-router
                registry: ghcr.io
                registry_username: __token__
                registry_password: ${{ secrets.GITHUB_TOKEN }}
